version: '2'
# Inspired by https://hub.docker.com/r/soloman1124/dynamodb-titan/
# Use the following gremlin command to connect to the titan DB instance (include the ':').
# :remote connect tinkerpop.server conf/remote.yaml
services:
  titan_server:
    image: soloman1124/dynamodb-titan
    links:
      - dynamodb
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    ports:
      - 8182:8182
  dynamodb:
    image: peopleperhour/dynamodb:latest
    ports:
      - 8000:8000
    entrypoint:
      - java
      - -Djava.library.path=.
      - -jar
      - DynamoDBLocal.jar
      - -dbPath
      - /var/dynamodb_local
      - -port
      - "8000"