version: '2'
# Use the following gremlin command to connect to the janusgraph DB instance (include the ':').
# :remote connect tinkerpop.server conf/remote.yaml
# To execute just the gremlin console: docker-compose run janusgraph_server console
services:
  janusgraph_server:
    image: bongo-janusgraph
    build:
      context: .
      args:
        DYNAMODB_ENDPOINT: http://dynamodb:8000
    links:
      - dynamodb
    ports:
      - 8182:8182
  dynamodb:
    image: peopleperhour/dynamodb:latest
    ports:
      - 8000:8000
    entrypoint:
      - java
      - -Djava.library.path=.
      - -jar
      - DynamoDBLocal.jar
      - -dbPath
      - /var/dynamodb_local
      - -port
      - "8000"